//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemasFAST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public film()
        {
            this.directions = new HashSet<direction>();
            this.estpresentes = new HashSet<estpresente>();
            this.roles = new HashSet<role>();
        }
    
        public int id { get; set; }
        public string titre { get; set; }
        public string description { get; set; }
        public Nullable<int> annee { get; set; }
        public int duree { get; set; }
        public Nullable<double> note { get; set; }
        public Nullable<int> nbr_votes { get; set; }
        public Nullable<double> revenue { get; set; }
        public Nullable<int> id_genre { get; set; }
        public string image { get; set; }
        public string type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<direction> directions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estpresente> estpresentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> roles { get; set; }
        public virtual genre genre { get; set; }
    }
}
