//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemasFAST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public seance()
        {
            this.estpresentes = new HashSet<estpresente>();
        }
    
        public int id { get; set; }
        public System.DateTime heure_debut { get; set; }
        public System.DateTime heure_fin { get; set; }
        public string nom_seance { get; set; }
        public int id_salle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<estpresente> estpresentes { get; set; }
        public virtual salle salle { get; set; }
    }
}
