//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemasFAST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplement
    {
        public int id { get; set; }
        public bool C3d { get; set; }
        public bool ultra_avx { get; set; }
        public bool dbox { get; set; }
        public bool imax { get; set; }
        public int id_salle { get; set; }
    
        public virtual salle salle { get; set; }
    }
}
