//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemasFAST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifs
    {
        public int id { get; set; }
        public double prix_adulte { get; set; }
        public double prix_enfant { get; set; }
        public double prix_aine { get; set; }
        public double prix_3d { get; set; }
        public double prix_ultra_avx { get; set; }
        public double prix_dbox { get; set; }
        public double prix_imax { get; set; }
        public int id_cinema { get; set; }
    
        public virtual cinema cinema { get; set; }
    }
}
